= AImage API Documentation
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 3
:sectlinks:
:docinfo: shared-head

== Overview

=== 공통 에러 응답

----
HTTP/1.1 400 Bad Request
Content-Type: text/plain;charset=UTF-8
Content-Length:

{
    "errors": [
        {
            "field": "...",
            "message": "..."
        }
    ]
}
----


== User APIs

=== 회원가입
operation::users/signup[snippets='request-fields,http-request,response-fields,http-response']


=== 로그인
operation::users/login[snippets='request-fields,http-request,response-fields,http-response']


=== 비밀번호 변경 전 사용자 확인
operation::users/pw-inquiry[snippets='request-fields,http-request,response-fields,http-response']


=== 닉네임 변경
operation::users/new-username[snippets='request-fields,http-request,response-fields,http-response']


=== 비밀번호 변경
operation::users/new-pw[snippets='request-fields,http-request,response-fields,http-response']


=== 계정 삭제
operation::users/delete-account[snippets='http-request,http-response']


== Image APIs

=== 이미지 저장
operation::images/new-image[snippets='request-fields,http-request,response-fields,http-response']


=== 단일 이미지 삭제
operation::images/delete-image[snippets='http-request,http-response']
