language: java
jdk:
  - openjdk17

branches:
  only:
    - main

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r aimage *
  - mkdir -p deploy
  - mv aimage.zip deploy/aimage.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY  # Travis repo setting에서 설정한 값
    secret_access_key: $AWS_SECRET_KEY  # Travis repo setting에서 설정한 값
    bucket: aimage-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private  # zip 파일 접근 권한 -> private
    local_dir: deploy # before_deploy 에서 생성한 디렉토리
    wait-until-deployed: true
    on:
      branch: main

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: aimage-build
    key: aimage.zip
    bundle_type: zip
    application: aimage
    deployment_group: aimage-group
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      branch: main

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - dyoon0807@gmail.com