package com.aimage.web.controller;

import com.aimage.domain.image.Image;
import com.aimage.domain.image.ImageRepository;
import com.theokanning.openai.completion.CompletionRequest;
import com.theokanning.openai.image.CreateImageRequest;
import com.theokanning.openai.service.*;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@Slf4j
@Controller
@RequiredArgsConstructor
public class BaseController {

    private final ImageRepository imageRepository;

    @GetMapping("/generate")
    public String generateForm(Model model) {
        model.addAttribute("image", new Image());
        return "features/generator";
    }

    @PostMapping("/result")
    public String generate(@ModelAttribute Image image, Model model) {
        log.info("Image generated: {}", image);

        String imageUrl = openAiImageUrl(image);
        image.setUrl(imageUrl);
        imageRepository.save(image);

        model.addAttribute("imageUrl", imageUrl);
        return "features/result";
    }

    /**
     *
     * @param imageToRequest Image details to request
     * @return An Image URL generated by OpenAI model.
     *
     * Library used: openai-java by Theo Kanning
     */
    private static String openAiImageUrl(Image imageToRequest) {
        OpenAiService service = new OpenAiService("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");
        CreateImageRequest createImageRequest = CreateImageRequest.builder()
                .prompt(imageToRequest.getPrompt())
                .n(1)
                .size(imageToRequest.getSize())
                .build();

        String imgUrl = service.createImage(createImageRequest)
                .getData()
                .get(0)
                .getUrl();

        return imgUrl;
    }
}
